# Generated by Django 3.2.2 on 2021-05-18 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120, verbose_name='Имя товара')),
                ('img', models.ImageField(default='default.png', upload_to='goods_img', verbose_name='Превью изображение')),
                ('description', models.TextField(default=' ', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Accessories',
                'verbose_name_plural': 'Accessories',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': '1Категории',
                'verbose_name_plural': '1Категории',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='default.png', upload_to='colors', verbose_name='Превью изображение')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120, verbose_name='Название цвета')),
            ],
        ),
        migrations.CreateModel(
            name='IPhone_Ipad_Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120, verbose_name='Имя товара')),
                ('TwoSimTrue', models.BooleanField(default=False, verbose_name='Наличие 2ух Симок')),
                ('IpadVersion', models.BooleanField(default=False, verbose_name='Есть ли 2 версии')),
                ('img', models.ImageField(default='default.png', upload_to='goods_img', verbose_name='Превью изображение')),
                ('description', models.TextField(default=' ', verbose_name='Описание')),
                ('img_description', models.ImageField(default='default.png', upload_to='goods_img', verbose_name='В комплекте')),
                ('MemoryVolume1', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Объем памяти 1')),
                ('MemoryVolume2', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Объем памяти 2(При наличие)')),
                ('MemoryVolume3', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Объем памяти 3(При наличие)')),
                ('MemoryVolume4', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Объем памяти 4(При наличие)')),
                ('RAM1', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Объем Оперативной памяти 1')),
                ('RAM2', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Объем Оперативной памяти 2')),
                ('RAM3', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Объем Оперативной памяти 3')),
                ('processor1', models.CharField(blank=True, max_length=120, null=True, verbose_name='Процессор 1')),
                ('processor2', models.CharField(blank=True, max_length=120, null=True, verbose_name='Процессор 2')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
                ('сolor1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color1', to='shop.color', verbose_name='Цвет1')),
                ('сolor2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color2', to='shop.color', verbose_name='Цвет2')),
                ('сolor3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color3', to='shop.color', verbose_name='Цвет3')),
                ('сolor4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color4', to='shop.color', verbose_name='Цвет4')),
                ('сolor5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color5', to='shop.color', verbose_name='Цвет5')),
                ('сolor6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color6', to='shop.color', verbose_name='Цвет6')),
            ],
            options={
                'verbose_name': 'iPhone+iPad+Mac',
                'verbose_name_plural': 'iPhones+iPads+Macs',
            },
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120, verbose_name='Имя товара')),
                ('img', models.ImageField(default='default.png', upload_to='goods_img', verbose_name='Превью изображение')),
                ('description', models.TextField(default=' ', verbose_name='Описание')),
                ('img_description', models.ImageField(default='default.png', upload_to='goods_img', verbose_name='В комплекте')),
                ('size_corps1', models.CharField(blank=True, max_length=120, null=True, verbose_name='Размер корпуса 1')),
                ('size_corps2', models.CharField(blank=True, max_length=120, null=True, verbose_name='Размер корпуса 2')),
                ('version1', models.CharField(blank=True, max_length=120, null=True, verbose_name='Версия 1')),
                ('version2', models.CharField(blank=True, max_length=120, null=True, verbose_name='Версия 2')),
                ('belt1', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ремень 1')),
                ('belt2', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ремень 2')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
                ('сolor1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color11', to='shop.color', verbose_name='Цвет1')),
                ('сolor2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color21', to='shop.color', verbose_name='Цвет2')),
                ('сolor3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color31', to='shop.color', verbose_name='Цвет3')),
                ('сolor4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color41', to='shop.color', verbose_name='Цвет4')),
                ('сolor5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color51', to='shop.color', verbose_name='Цвет5')),
                ('сolor6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color61', to='shop.color', verbose_name='Цвет6')),
            ],
            options={
                'verbose_name': 'Watch',
                'verbose_name_plural': 'Watch',
            },
        ),
        migrations.CreateModel(
            name='WatchPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorСode', models.CharField(max_length=120, verbose_name='Артикул')),
                ('size', models.CharField(blank=True, max_length=120, null=True, verbose_name='Размер корпуса')),
                ('version', models.CharField(blank=True, max_length=120, null=True, verbose_name='Версия')),
                ('belt', models.CharField(blank=True, max_length=120, null=True, verbose_name='Тип ремешка')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='Доп ценна за цвет')),
                ('imgMain', models.ImageField(default='default.png', upload_to='goods_img', verbose_name='Фото айфона')),
                ('anchor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.watch', verbose_name='Модель привязки')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.color', verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Watch Товары',
                'verbose_name_plural': 'Watch Товары',
            },
        ),
        migrations.CreateModel(
            name='IPhonePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorСode', models.CharField(max_length=120, verbose_name='Артикул')),
                ('sim', models.IntegerField(choices=[[1, '1 Sim'], [2, 's Sim']], default=1)),
                ('MemoryVolume', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Объем памяти')),
                ('imgMain', models.ImageField(default='default.png', upload_to='goods_img', verbose_name='Фото айфона')),
                ('version', models.IntegerField(blank=True, choices=[[1, 'Wi-Fi'], [2, 'Wi-Fi + 4G']], default=1, null=True, verbose_name='Версия Айпада')),
                ('ram', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Объем оперативной памяти')),
                ('processor1', models.CharField(blank=True, max_length=120, null=True, verbose_name='Процессор')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='Доп ценна за цвет')),
                ('anchor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.iphone_ipad_main', verbose_name='Модель привязки')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.color', verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'iPhone+iPad+Mac Товары',
                'verbose_name_plural': 'iPhones+iPads+Macs Товары',
            },
        ),
        migrations.CreateModel(
            name='airPodsPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorСode', models.CharField(max_length=120, verbose_name='Артикул')),
                ('coverings', models.CharField(blank=True, max_length=120, null=True, verbose_name='Покрытия')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='Доп ценна за цвет')),
                ('imgMain', models.ImageField(default='default.png', upload_to='goods_img', verbose_name='Фото айфона')),
                ('anchor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.watch', verbose_name='Модель привязки')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.color', verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'airPods Товары',
                'verbose_name_plural': 'airPods Товары',
            },
        ),
        migrations.CreateModel(
            name='airPods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=120, verbose_name='Имя товара')),
                ('img', models.ImageField(default='default.png', upload_to='goods_img', verbose_name='Превью изображение')),
                ('description', models.TextField(default=' ', verbose_name='Описание')),
                ('img_description', models.ImageField(default='default.png', upload_to='goods_img', verbose_name='В комплекте')),
                ('coverings1', models.CharField(blank=True, max_length=120, null=True, verbose_name='Покрытия 1')),
                ('coverings2', models.CharField(blank=True, max_length=120, null=True, verbose_name='Покрытия 2')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория')),
                ('сolor1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color12', to='shop.color', verbose_name='Цвет1')),
                ('сolor2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color22', to='shop.color', verbose_name='Цвет2')),
                ('сolor3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color32', to='shop.color', verbose_name='Цвет3')),
                ('сolor4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color42', to='shop.color', verbose_name='Цвет4')),
                ('сolor5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color52', to='shop.color', verbose_name='Цвет5')),
                ('сolor6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color62', to='shop.color', verbose_name='Цвет6')),
            ],
            options={
                'verbose_name': 'airPods',
                'verbose_name_plural': 'airPods',
            },
        ),
        migrations.CreateModel(
            name='AccessoriesPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorСode', models.CharField(max_length=120, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=5, verbose_name='Доп ценна за цвет')),
                ('imgMain', models.ImageField(default='default.png', upload_to='goods_img', verbose_name='Фото айфона')),
                ('anchor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.accessories', verbose_name='Модель привязки')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.color', verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Accessories Товары',
                'verbose_name_plural': 'Accessories Товары',
            },
        ),
        migrations.AddField(
            model_name='accessories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='сolor1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color13', to='shop.color', verbose_name='Цвет1'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='сolor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color23', to='shop.color', verbose_name='Цвет2'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='сolor3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color33', to='shop.color', verbose_name='Цвет3'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='сolor4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color43', to='shop.color', verbose_name='Цвет4'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='сolor5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color53', to='shop.color', verbose_name='Цвет5'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='сolor6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color63', to='shop.color', verbose_name='Цвет6'),
        ),
    ]
