# Generated by Django 3.2.2 on 2021-05-19 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('color', models.CharField(max_length=128)),
                ('TwoSimTrue', models.BooleanField(default=False, verbose_name='Наличие 2ух Симок')),
                ('IpadVersion', models.BooleanField(default=False, verbose_name='Есть ли 2 версии')),
                ('MemoryVolume', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('RAM', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('processor', models.CharField(blank=True, max_length=120, null=True)),
                ('size_corps', models.CharField(blank=True, max_length=120, null=True)),
                ('version', models.CharField(blank=True, max_length=120, null=True)),
                ('belt', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ремень')),
                ('price', models.DecimalField(decimal_places=0, max_digits=9, verbose_name='Цена')),
                ('quantity', models.IntegerField(default=1, verbose_name='Количество')),
                ('img_url', models.CharField(max_length=120, verbose_name='Ссылка на img')),
                ('article_date', models.DateTimeField(default=datetime.datetime(2021, 5, 19, 17, 57, 29, 342307))),
            ],
        ),
    ]
