# Generated by Django 3.2.2 on 2021-05-19 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='TwoSimTrue',
            field=models.CharField(default=1, max_length=128),
        ),
        migrations.AlterField(
            model_name='basket',
            name='article_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 18, 11, 5, 454986)),
        ),
    ]
