# Generated by Django 3.2.2 on 2021-05-23 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_basket_article_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('address', models.CharField(max_length=120, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=120, verbose_name='Адрес')),
                ('description', models.TextField(default=' ', verbose_name='Описание')),
                ('info', models.TextField(default=' ', verbose_name='Описание')),
            ],
        ),
        migrations.AlterField(
            model_name='basket',
            name='IpadVersion',
            field=models.BooleanField(default=1, max_length=128),
        ),
        migrations.AlterField(
            model_name='basket',
            name='article_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 24, 0, 5, 48, 521960)),
        ),
    ]
