# Generated by Django 3.2.2 on 2021-05-27 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210524_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='basket',
            name='article_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 28, 1, 52, 36, 130615)),
        ),
        migrations.AlterField(
            model_name='iphonepart',
            name='version',
            field=models.CharField(blank=True, choices=[['Wi-Fi', 'Wi-Fi'], ['Wi-Fi + 4G', 'Wi-Fi + 4G']], max_length=120, null=True, verbose_name='Версия Айпада'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(default=' ', verbose_name='Коментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='info',
            field=models.TextField(default=' ', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=120, verbose_name='Телефон'),
        ),
    ]
