# Generated by Django 3.2.2 on 2021-05-29 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210528_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='airpods',
            name='charging1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Зарядка 1'),
        ),
        migrations.AddField(
            model_name='airpods',
            name='charging2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Зарядка 2'),
        ),
        migrations.AddField(
            model_name='airpods',
            name='connector1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Разъем 1'),
        ),
        migrations.AddField(
            model_name='airpods',
            name='connector2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Разъем 2'),
        ),
        migrations.AddField(
            model_name='airpodspart',
            name='charging',
            field=models.CharField(blank=True, default='-', max_length=120, null=True, verbose_name='Зарядка'),
        ),
        migrations.AddField(
            model_name='airpodspart',
            name='connector',
            field=models.CharField(blank=True, default='-', max_length=120, null=True, verbose_name='Разъем'),
        ),
        migrations.AddField(
            model_name='basket',
            name='charging',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Зарядка'),
        ),
        migrations.AddField(
            model_name='basket',
            name='connector',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Разъем'),
        ),
        migrations.AddField(
            model_name='basket',
            name='coverings',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Покрытия'),
        ),
        migrations.AlterField(
            model_name='airpodspart',
            name='coverings',
            field=models.CharField(blank=True, default='-', max_length=120, null=True, verbose_name='Покрытия'),
        ),
        migrations.AlterField(
            model_name='airpodspart',
            name='vendorСode',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='article_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 30, 2, 50, 29, 947294)),
        ),
    ]
