# Generated by Django 3.2.2 on 2021-05-30 22:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210530_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airpodspart',
            name='anchor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.airpods', verbose_name='Модель привязки'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='article_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 1, 33, 21, 49888)),
        ),
    ]
