# Generated by Django 3.2.2 on 2021-05-30 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210531_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='MemoryVolume1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Объем памяти 1(При наличие)'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='MemoryVolume2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Объем памяти 2(При наличие)'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='modelCase1',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Модель привязки чехла 1'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='modelCase2',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Модель привязки чехла 2'),
        ),
        migrations.AddField(
            model_name='accessories',
            name='modelCase3',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Модель привязки чехла 3'),
        ),
        migrations.AddField(
            model_name='accessoriespart',
            name='MemoryVolume',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Объем памяти(При наличие)'),
        ),
        migrations.AddField(
            model_name='accessoriespart',
            name='modelCase',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Модель привязки чехла'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='article_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 2, 59, 0, 580852)),
        ),
    ]
